# use the official node 20 image from the Docker Hub with alpine base image

FROM node:20-alpine

# set the working directory in the container
WORKDIR /use/src/app

# copy package.json and package-lock.json
COPY package*.json ./

# install production dependencies no dev dependencies
RUN npm ci  --only=production

# copy the rest of the application code
COPY . .

EXPOSE 3003

CMD [ "node", "src/server.js" ]